version: "3"

networks:
  networker:
    driver: bridge 

services:
  mysql:
    container_name: dnmp-mysql
    build:
      context: ./docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/lib:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - networker

  redis:
    container_name: dnmp-redis
    build:
      context: ./docker/redis/
      args:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - networker

  php:
    container_name: dnmp-php
    build:
      context: ./docker/php/
    volumes: 
      - ./html:/var/www/html
      - ./data/php/supervisord.d:/etc/supervisor/supervisord.d
      - ./data/php/cron.d:/etc/cron.d
      - ./data/php/certs:/root/.acme.sh/certs
    depends_on:
      - mysql
      - redis
    networks:
      - networker

  php-fpm:
    container_name: dnmp-php-fpm
    build:
      context: ./docker/php-fpm/
    volumes:
      - ./html:/var/www/html
      - ./data/php-fpm/log:/var/log/php
    depends_on:
      - mysql
      - redis
    networks:
      - networker

  nginx:
    container_name: dnmp-nginx
    build:
      context: ./docker/nginx/
    volumes:
      - ./html:/var/www/html
      - ./data/nginx/log:/var/log/nginx
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/work/certs:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - networker

