version: "3"

networks:
  www-network:
    driver: bridge 

services:
  mysql:
    container_name: dnmp-mysql
    build:
      context: ./docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql/lib:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - www-network

  redis:
    container_name: dnmp-redis
    build:
      context: ./docker/redis/
    volumes:
      - ./data/redis/dump.rdb:/data/dump.rdb
    ports:
      - "6379:6379"
    networks:
      - www-network

  work:
    container_name: dnmp-work
    build:
      context: ./docker/work/
    volumes: 
      - ./www:/var/www
      - ./data/work/supervisord.d:/etc/supervisor/supervisord.d
      - ./data/work/cron.d:/etc/cron.d
    depends_on:
      - mysql
      - redis
    networks:
      - www-network

  php:
    container_name: dnmp-php
    build:
      context: ./docker/php/
    volumes:
      - ./www:/var/www
      - ./data/php/log:/var/log/php
    depends_on:
      - mysql
      - redis
    networks:
      - www-network

  nginx:
    container_name: dnmp-nginx
    build:
      context: ./docker/nginx/
    volumes:
      - ./www:/var/www
      - ./data/nginx/log:/var/log/nginx
      - ./data/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - www-network

