version: "3"

networks:
  www-network:
    driver: bridge 

services:
  mysql:
    container_name: dnmp-mysql
    build:
      context: ./docker/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./log/mysql/:/var/log/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - www-network

  redis:
    container_name: dnmp-redis
    build:
      context: ./docker/redis/
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - www-network

  work:
    container_name: dnmp-work
    build:
      context: ./docker/work/
    volumes: 
      - ./www/:/var/www
      - ./conf/work/php.ini:/usr/local/etc/php/php.ini
      - ./conf/work/supervisord.conf:/etc/supervisor/supervisord.conf
    depends_on:
      - mysql
      - redis
    networks:
      - www-network

  php:
    container_name: dnmp-php
    build:
      context: ./docker/php/
    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./log/php:/var/log/php
    depends_on:
      - mysql
      - redis
    networks:
      - www-network

  nginx:
    container_name: dnmp-nginx
    build:
      context: ./docker/nginx/
    volumes:
      - ./www/:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d
      - ./log/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - www-network

